# Minimal docker container to build project
# Image: ipittau/qt:5.12-desktop

FROM rabits/qt:5.12-desktop
MAINTAINER Ilario <ilariopittau@gmail.com> (@ipittau)

apt-get -qq update && apt-get -qq install -y gcovr ggcov lcov
